### ISSUE TITLE
Strange BSD License mapping for pytest_cov-2.7.1-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by brunopacheco1** [oss-review-toolkit/ort-config#152]
# Summary

I am [reviewing licenses](https://github.com/GenomicDataInfrastructure/gdi-userportal-ort) with OSS Review Toolkit and [this report](https://github.com/GenomicDataInfrastructure/gdi-userportal-ort/suites/18904049789/artifacts/1103865357) shows the message below.

`pytest_cov` is under MIT, but this file `pytest_cov-2.7.1-py2.py3-none-any.whl` is under BSD License. How is that possible?

<img width="688" alt="Screenshot 2023-12-11 at 13 36 28" src="https://github.com/oss-review-toolkit/ort-config/assets/4491850/279ef70f-3d69-464b-9be5-3e33f5546614">

## Expected vs actual result

Everything should be under MIT. Or we should not check license of `.whl` files. What do you suggest to do?

# Reproducer

Run ORT on a project that depends on `pytest_cov==2.7.1`.

**Comment by sschuberth** [comment]
This was addressed by https://github.com/oss-review-toolkit/ort-config/pull/159.
