### ISSUE TITLE
Rule violation on vulnerability is not getting triggered 

### ISSUE THREAD

**Issue by saaskesaakura345** [oss-review-toolkit/ort-config#189]
Hi Team,

I am facing issues with raising rule violations for vulnerable components in my dependencies.
I am using the existing evaluator.kts file from this repository and it triggers rule violations for license issues but not for vulnerabilities.

As seen below vulnerabilities are identified, but not brought out in the "Rule Violations" tab.
![image](https://github.com/oss-review-toolkit/ort-config/assets/128026849/fc487030-9800-4be5-ba4d-536e8cae94a4)

The action file used is : https://github.com/oss-review-toolkit/ort-ci-github-action

Can someone guide me to understand what i am missing or any reference to the solution.

**Comment by sschuberth** [comment]
As @tsteenbe pointed out, this is probably related to the example rule to [only trigger for the CVSS2 scoring system](https://github.com/oss-review-toolkit/ort-config/blob/31c785fb2e1c707ee0ac65f3e2a383b048455e84/evaluator.rules.kts#L1488).

**Comment by tsteenbe** [comment]
See for example https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-67hx-6x53-jw92/GHSA-67hx-6x53-jw92.json#L13 propose we update the rule to trigger for CVSSv2 or make the rule that it trigger for any form of CVSS

**Comment by sschuberth** [comment]
> update the rule to trigger for CVSSv2

That should say "CVSSv3", I believe.
