### ISSUE TITLE
Documentation of config.yml

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [oss-review-toolkit/ort-config#196]
Hi there,
is there a documentation for the `config.yml` somewhere? I could not find any. There is [this reference file](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/resources/reference.yml) which is far from complete. For example I have no idea how to configure the report generation with it. Could you please point me in the right direction?

The same is true for `analyzer`. I can set the format, input and output in the terminal with `analyze -f JSON -i /project/src -o /project/ORT`. But how can I do that with the config file?

Best regards,
Georg

**Comment by georg-eckert-zeiss** [comment]
PS: Does it just map to the config files like [AnalyzerConfiguration.kt](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/config/AnalyzerConfiguration.kt)?

**Comment by sschuberth** [comment]
> There is [this reference file](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/resources/reference.yml)

There is currently no more documentation than that, unless you additionally want to [look at the code](https://github.com/oss-review-toolkit/ort/blob/0b703b83ecdfddd639e65184de6d41d946cbfe60/model/src/main/kotlin/config/OrtConfiguration.kt#L38-L41).

> Does it just map to the config files like [AnalyzerConfiguration.kt](https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/kotlin/config/AnalyzerConfiguration.kt)?

Yes, as [`AnalyzerConfiguration` is just part of the aforementioned `OrtConfiguration`](https://github.com/oss-review-toolkit/ort/blob/0b703b83ecdfddd639e65184de6d41d946cbfe60/model/src/main/kotlin/config/OrtConfiguration.kt#L115-L118).

**Comment by sschuberth** [comment]
> For example I have no idea how to configure the report generation with it. Could you please point me in the right direction?

Although there already was [an example for the `FossIdReporter`](https://github.com/oss-review-toolkit/ort/blob/0b703b83ecdfddd639e65184de6d41d946cbfe60/model/src/main/resources/reference.yml#L371-L378), I've now added [another one for `CycloneDx`](https://github.com/oss-review-toolkit/ort/pull/8736/commits/9cbdd2554680bfeec691819273ba7dfdf71847eb). What exact option for which reporter were you looking for?

**Comment by georg-eckert-zeiss** [comment]
Just the local ones. Export as Text file or HTML.

**Comment by sschuberth** [comment]
> Just the local ones.

All but the FossId reporters are "local" ones. In that sense, the existing FossId example was probably bad, as it was the most complicated one 😉

**Comment by georg-eckert-zeiss** [comment]
Ok.Thanks.
