### ISSUE TITLE
Add a Gradle task for generating a `license-classifications.yml` from ScanCode's license data

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort-config#59]
Make it easy to use ScanCode's license categorization in ORT.

This can make use of https://scancode-licensedb.aboutcode.org/index.json.

**Comment by sschuberth** [comment]
Just FYI, there's already @maxhbr's somewhat similar generated https://github.com/maxhbr/LDBcollector/blob/generated/ort/license-classifications.yml for ORT.

**Comment by maxhbr** [comment]
the code in https://github.com/maxhbr/LDBcollector/blob/generated/ort/license-classifications.yml contains the classification from ScanCode and other sources. (Just restricting LDBcollector to ScanCode could even produce what you look for.)

**Comment by fviernau** [comment]
Follow-up: #66.
